# fly.web.toml
app = "skywatched"
primary_region = "lax"

[build]
  # passing the PROJECT arg as "web"
  [build.args]
    PROJECT = "web"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
